import { useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import Footer from "~/components/Footer";
import LoadingPage from "~/components/LoadingPage";
import Nav from "~/components/Nav";
import ProductCard from "~/components/ProductCard";
import { api } from "~/utils/api";

const Feed = () => {
  const { data, isLoading: productsLoading } = api.products.getAll.useQuery();

  if (productsLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong...</div>;

  return (
    <div>
      {data?.map((fullProduct) => (
        <ProductCard {...fullProduct} key={fullProduct.id} />
      ))}
    </div>
  );
};

// type PostWithUser = RouterOutputs["posts"]["getAll"][number];
// const PostView = (props: PostWithUser) => {

const ShopPage: NextPage = () => {
  const { isLoaded: userLoaded } = useUser();

  // console.log(user); from useUser()

  // Start fetching asap
  api.products.getAll.useQuery();

  // Return empty div if user isn't loaded yet
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col justify-between">
        <Nav />

        <section className="flex flex-wrap justify-center">
          <Feed />
        </section>
        <Footer />
      </main>
    </>
  );
};

export default ShopPage;
