import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import Nav from "~/components/Nav";
import { api } from "~/utils/api";

const ShopPage: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  // console.log(user); from useUser()

  // Start fetching asap
  api.posts.getAll.useQuery();

  // Return empty div if user isn't loaded yet
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <Nav />
      </main>
    </>
  );
};

export default ShopPage;
