import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
// import Link from "next/link";

import { api } from "~/utils/api";
// import type { RouterOutputs } from "~/utils/api";

// import dayjs from "dayjs";
// import relativeTime from "dayjs/plugin/relativeTime";
// import LoadingPage from "~/components/LoadingPage";

const SinglePostPage: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  // console.log(user); from useUser()

  // Start fetching asap
  api.posts.getAll.useQuery();

  // Return empty div if user isn't loaded yet
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex justify-center border-b border-slate-400 p-4">
            {!isSignedIn && <SignInButton />}
            {!!isSignedIn && <SignOutButton />}
          </div>
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
