import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Footer from "~/components/Footer";
import MButton from "~/components/MButton";
import Nav from "~/components/Nav";

const CancelPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Canceled Order</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col justify-between">
        <Nav />

        <section className="flex flex-col items-center">
          {/* <Feed /> */}
          <h2 className="p-2 text-xl font-semibold md:p-4 md:text-2xl">
            Don't Worry! We saved your cart!
          </h2>

          <Link href={"/shop"}>
            <button type="button" className="mojave font-semibold md:hidden">
              Keep Shopping
            </button>
            <MButton>Keep Shopping</MButton>
          </Link>
        </section>
        <Footer />
      </main>
    </>
  );
};

export default CancelPage;
